### ISSUE TITLE
Add action example

### ISSUE THREAD

**Issue by JavierPozoDelevoper** [a-giuliano/stencil-storybook-html#3]
Based on this example I have been trying to add a log with an "onclick" action on a Stencil component but I can't get it to show up in the storybook.

Could you add an example of how to add actions in a story to this repository?
[Documentation of storybook actions](https://storybook.js.org/docs/react/essentials/actions)

Thx.

**Comment by a-giuliano** [comment]
Hey @JavierPozoDelevoper! This is a great question. I've created #4 to demonstrate how to add actions. Let me know if this is a helpful example.

**Comment by JavierPozoDelevoper** [comment]
Hey @a-giuliano ! This works for me. 
Before your example I was using the old way of creating stories and this optimizes my code a lot.
Thank you very much.

**Comment by a-giuliano** [comment]
Oh I'm so glad it's helpful!
